config/routes.rb
Rails.application.routes.draw do
  resources :loadouts
  resources :ingredients
  require 'sidekiq/web'

  mount SimpleDiscussion::Engine => "/forum"
  mount ActionCable.server => '/cable'

  authenticate :user, ->(op) { op.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'static_pages#about'

  resources :locations
  resources :respawns
  resources :modes
  resources :characters
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', 
                            registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
  resources :games
  resources :levels
  resources :directions
  resources :recipes
  resources :rooms
  resources :teams
  resources :objectives
  resources :strategies

  get '/about' => 'static_pages#about'
  get '/docs' => 'static_pages#docs'
  get '/strategies/xml/:uuid' => 'strategies#show_xml', as: 'strategy_xml'
  patch '/games/:id/switch/' => 'games#switch', as: 'switch_game'
  put '/users/api_key' => 'users#create_api_key', as: 'api_key'
  put '/teams/:id/link/:game_id' => 'teams#link_game', as: 'game_link'
  delete '/teams/:id/link/:game_id' => 'teams#unlink_game', as: 'game_unlink'
  post 'teams/:id/join' => 'teams#join_team', as: 'join_team'
  post 'teams/:id/change_title' => 'teams#change_member_title',
       as: 'change_member_title'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :commander, class_name: 'User'
  belongs_to :objective, optional: true
  has_many :directions, dependent: :delete_all
  has_many :ingredients, dependent: :delete_all
  has_many :user_recipes, dependent: :delete_all
  has_many :users, through: :user_recipes
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_variables, only: [:new, :show, :edit]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @directions = @recipe.directions
    @ingredients = @recipe.ingredients
    @direction = Direction.new
    @ingredient = Ingredient.new
    @primaries = set_loadout('Primary')
    @secondaries = set_loadout('Secondary')
    @sights = set_loadout('Sight')
    @grips = set_loadout('Grip')
    @attachments = set_loadout('Attachment')
    @utilities = set_loadout('Utility')
    loadouts = @recipe.ingredients.where(piece_type: 'Loadout')

    @parents = loadouts.select do |ingredient|
      ingredient.piece.kind == 'Secondary' || ingredient.piece.kind == 'Primary'
    end
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.uuid = SecureRandom.uuid
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe.objective}
        format.json { render :show, status: :created, location: @recipe.objective }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    authorize @recipe
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    authorize @recipe
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url}
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params[:recipe][:commander_id] = current_user.id
      params.fetch(:recipe, {}).permit(:name, :objective_id, :commander_id)
    end

    def set_variables
      params_obj = params[:obj]
      @objective = params_obj ? Objective.find(params_obj) : @recipe.objective
      @strategy = @objective.strategy
      @game = @strategy.game
    end

    def set_loadout(kind)
      @game.loadouts.where(kind: kind).reject do |target|
        ids = @recipe.ingredients.where(piece_type: 'Loadout').pluck(:piece_id)

        ids.include?(target.id)
      end 
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_with(model: recipe, local: true) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :objective, class:"label" %><br>
    <div class="select">
      <%= form.collection_select :objective_id, 
                        Objective.all, 
                        :id, 
                        :name,
                        required: true,
                        selected: @objective.id %>
    </div>
  </div>

  <div class="field">
    <%= form.label :name, class:"label" %><br />
    <%= form.text_field :name, autofocus: true, required: true, class:"input" %>
  </div>

  <div class="actions">
    <%= form.submit class:"button is-link is-pulled-left" %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'shared/breadcrumb' %>

<div class="columns is-centered">
  <div class="column is-one-third">
    <% if policy(@recipe).destroy? %>	
      <%= link_to "Delete recipe", recipe_path(@recipe), 	
                        method: :delete,	
                        data: { 	
                          confirm: 	
                          "Are you sure you want to delete #{@recipe.name}?" 	
                        }, 	
                        class: "button is-black is-pulled-right is-small is-rounded" %>	
    <% end %>

    <h1 class="title is-5">Editing Recipe</h1>

    <%= render 'form', recipe: @recipe %>
    <%= link_to 'Cancel', recipe_path(@recipe), class:"is-pulled-right button is-black" %>
  </div>
</div>

app/views/recipes/index.html.erb
<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<%= render 'shared/breadcrumb'%>

<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
<%= render 'shared/breadcrumb'%>


<div class="columns is-centered">
  <div class="column is-narrow">
    <div class="box">
      <% if policy(@recipe).update? %>
        <%= link_to "Edit", edit_recipe_path(@recipe), 
                          class: 'button is-small is-rounded is-pulled-left'%>
      <% end %>
      <h1 class="title is-5 has-text-centered">
        <%= "#{controller_name.capitalize.singularize}" %>
      </h1>
      <table class="table is-striped">
        <caption>Recipe Attributes</caption>
        <tr>
          <th>Name</th>
          <td><%= @recipe.name%></td>
        </tr>
        <tr>
          <th>Objective</th>
          <td><%= @objective.name%></td>
        </tr>
        <tr>
          <th>Strategy</th>
          <td><%= @strategy.name %></td>
        </tr>
        <tr>
          <th>Created By</th>
          <% commander = @recipe.commander%>
          <td><%= link_to commander.name, user_path(commander)%></td>
        </tr>
        <tr>
          <th>Created At</th>
          <td><%= @recipe.created_at%></td>
        </tr>
        <tr>
          <th>Updated At</th>
          <td><%= @recipe.updated_at %></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="column is-narrow">
    <div class="box">
      <% if policy(@recipe).update? %>
        <button class='button is-rounded is-small new-direction-btn'>
          New Direction
        </button>
      <% end %>
      <h2 class="title is-5">Directions</h2>
      <table class="table is-bordered">
        <thead>
          <tr>
            <th>Step</th>
            <th>Name</th>
          </tr>
        </thead>
        <tbody>
          <% @directions.each do |direction| %>
            <tr>
              <td>
                <%= direction.step %> 
              </td>
              <td>
                <%= link_to direction.name, direction_path(direction) %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="column is-narrow">
    <div class="box">
      <% if policy(@recipe).update? %>
        <button class='button is-rounded is-small new-ingredient-btn'>
          New Ingredient
        </button>
      <% end %>
      <h2 class="title is-5">Ingredients</h2>
      <table class="table is-bordered">
        <thead>
          <tr>
            <th>Kind</th>
            <th>Name</th>
            <th>Parent</th>
          </tr>
        </thead>
        <tbody>
          <% @ingredients.each do |ingredient| %>
            <tr>
              <td><%= ingredient.piece_type %></td>
              <td>
                <%= link_to ingredient.piece.name, ingredient_path(ingredient) %>
              </td>
              <td>
                <%= ingredient.parent ? ingredient.parent.piece.name : '----' %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head" >
      <p class="modal-card-title"></p>
      <button class="delete close-btn" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <div class="ingredient-form">
        <%= render '/ingredients/form', ingredient: @ingredient %>
      </div>
      <div class="direction-form">
        <%= render '/directions/form', direction: @direction %>
      </div>
    </section>
  </div>
</div>