config/routes.rb
Rails.application.routes.draw do
  resources :loadouts
  resources :ingredients
  require 'sidekiq/web'

  mount SimpleDiscussion::Engine => "/forum"
  mount ActionCable.server => '/cable'

  authenticate :user, ->(op) { op.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'static_pages#about'

  resources :locations
  resources :respawns
  resources :modes
  resources :characters
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', 
                            registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
  resources :games
  resources :levels
  resources :directions
  resources :recipes
  resources :rooms
  resources :teams
  resources :objectives
  resources :strategies

  get '/about' => 'static_pages#about'
  get '/docs' => 'static_pages#docs'
  get '/strategies/xml/:uuid' => 'strategies#show_xml', as: 'strategy_xml'
  patch '/games/:id/switch/' => 'games#switch', as: 'switch_game'
  put '/users/api_key' => 'users#create_api_key', as: 'api_key'
  put '/teams/:id/link/:game_id' => 'teams#link_game', as: 'game_link'
  delete '/teams/:id/link/:game_id' => 'teams#unlink_game', as: 'game_unlink'
  post 'teams/:id/join' => 'teams#join_team', as: 'join_team'
  post 'teams/:id/change_title' => 'teams#change_member_title',
       as: 'change_member_title'
end

app/models/objective.rb
class Objective < ApplicationRecord
  ACTION_OPTIONS = %w[Attack Defend Capture].freeze

  validates_inclusion_of :action, in: ACTION_OPTIONS

  belongs_to :strategy
  belongs_to :target,
             class_name: 'Location',
             optional: true
  belongs_to :master,
             class_name: 'Objective',
             foreign_key: 'master_id',
             optional: true
  belongs_to :next,
             class_name: 'Objective',
             foreign_key: 'next_id',
             optional: true
  has_many :previous,
           class_name: 'Objective',
           foreign_key: 'next_id', dependent: :nullify
  has_many :recipes, dependent: :nullify
  has_many :slaves,
           class_name: 'Objective',
           foreign_key: 'master_id', dependent: :nullify
  has_many :primaries,
           class_name: 'UserStrategy',
           foreign_key: 'primary_id',
           dependent: :nullify
  has_many :secondaries,
           class_name: 'UserStrategy',
           foreign_key: 'secondary_id',
           dependent: :nullify
  has_many :tertiaries,
           class_name: 'UserStrategy',
           foreign_key: 'tertiary_id',
           dependent: :nullify
  has_many :defaults,
           class_name: 'UserStrategy',
           foreign_key: 'default_id',
           dependent: :nullify
  has_many :user_strategies, dependent: :nullify
  has_many :current_ops,
           class_name: 'User',
           foreign_key: 'current_objective_id'
  after_commit { UpdateAssignmentFlowJob.perform_later(strategy) }
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: [:show, :edit, :update, :destroy]
  before_action :set_variables, only: [:show, :edit]
  before_action :set_strategy, only: [:show, :new, :edit]

  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
    @recipe = Recipe.new
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit; end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(objective_params)
    authorize @objective.strategy, :create_objective?
    @objective.uuid = SecureRandom.uuid
    direction = params[:objective][:direction]
    dependency = params[:objective][:dependency]
    next_id = params[:objective][:next_id]
    master_id = params[:objective][:master_id]
    @objective.next_id = nil if direction == "previous"
    @objective.master_id = nil if dependency == "slave"
  
    respond_to do |format|
      if @objective.save
        if direction == "previous" && next_id.to_i > 0
          @objective.previous.push Objective.find(next_id)
        end
        if dependency == "slave" && master_id.to_i > 0
          @objective.slaves.push Objective.find(master_id)
        end

        format.html { redirect_to @objective.strategy }
        format.json { render :show, status: :created, location: @objective.strategy }
      else
        format.html { render :new }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1
  # PATCH/PUT /objectives/1.json
  def update
    authorize @objective.strategy, :update_objective?
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to @objective}
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    authorize @objective.strategy
    @objective.destroy
    respond_to do |format|
      format.html { redirect_to objectives_url }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    def set_strategy
      strat = params[:strat]
      @strategy = strat ? Strategy.find(strat) : @objective.strategy
      @strategies = Strategy.all
      @locations = @strategy.level.locations
    end

    def set_variables
      @next = Objective.find(@objective.next_id) if @objective.next
      @master = Objective.find(@objective.master_id) if @objective.master
      @recipes = @objective.recipes
      @game = @objective.strategy.game
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objective_params
      # rubocop:disable Style/IfUnlessModifier
      if params[:objective][:strategy_id]
        params[:objective][:strategy_id] = params[:objective][:strategy_id].to_i
      end
      # rubocop:enable Style/IfUnlessModifier
      params.fetch(:objective, {}).permit(:name, :target_id, :action,
                                          :strategy_id, :min_ops, :max_ops,
                                          :priority, :next_id, :delay,
                                          :master_id)
    end
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.erb
<%= form_with(model: objective, local: true) do |form| %>
  <% if objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
      <% objective.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class:"label" %>
    <%= form.text_field :name, autofocus: true, required: true, class:"input" %>
  </div>

  <%= form.hidden_field :strategy_id, value: @strategy.id  %>

  <div class="field">
    <%= form.label :action, class:"label" %>
    <div class="select">
      <%= form.select :action, Objective::ACTION_OPTIONS, 
                              { :include_blank => '-- Select One --' },
                              required: true, class:"input" %>
    </div>
  </div>

  <div class="field">
    <%= form.label :target, class:"label" %>
    <div class="select">
      <%= form.collection_select :target_id, 
                                 @locations, 
                                 :id, 
                                 :name, 
                                 required: true,
                                 :include_blank => '-- Select One --'  %>
    </div>
  </div>

  <div class="field">
    <%= form.label :minimum_users, for: :min_ops, class:"label" %>
    <%= form.number_field :min_ops, min:1, max:100, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :maximum_users, for: :max_ops, class:"label" %>
    <%= form.number_field :max_ops, min:1, max:100, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :priority_level, for: :priority, class:"label"  %>
    <%= form.number_field :priority, min:1, max:10, class:"input" %>
  </div>

  <div class="field">
    <%= form.label :link_objective, for: :next_id, class:"label" %>
    <div class="select">
      <%= form.collection_select :next_id, 
                                 @strategy.objectives, 
                                 :id, 
                                 :name, 
                                 { :include_blank => '-- Optional --' }%>
    </div>
    <%= form.label :direction, value: :previous  %>
    <%= form.radio_button :direction, :previous, checked: true %>
    <%= form.label :direction, value: :next %>
    <%= form.radio_button :direction, :next%>
  </div>

  <div class="field">
    <%= form.label :dependency, class:"label" %>
    <div class="select">
      <%= form.collection_select :master_id, 
                                 @strategy.objectives, 
                                 :id, 
                                 :name, 
                                 { :include_blank => '-- Optional --' }%>
    </div>
    <%= form.label :dependency, :value => "master"  %>
    <%= form.radio_button :dependency, :master, checked: true %>
    <%= form.label :dependency, :value => "slave" %>
    <%= form.radio_button :dependency, :slave%>
  </div>

  <div class="field">
    <%= form.label "Delay(seconds)", for: :delay, class:"label" %>
    <%= form.number_field :delay, min:0, max:10_000, class:"input"%>
  </div>

  <div class="actions">
    <%= form.submit class:"button is-link is-pulled-left" %>
  </div>
<% end %>

app/views/objectives/edit.html.erb
<%= render 'shared/breadcrumb' %>

<div class="columns is-centered">
  <div class="column is-one-third">
    <% if policy(@objective.strategy).destroy? %>	
      <%= link_to "Delete objective", objective_path(@objective), 	
                        method: :delete,	
                        data: { 	
                          confirm: 	
                          "Are you sure you want to delete #{@objective.name}?" 	
                        }, 	
                        class: "button is-black is-pulled-right is-small is-rounded" %>	
    <% end %>

    <h1 class="title is-5">Editing Objective</h1>

    <%= render 'form', objective: @objective %>
    <%= link_to 'Cancel', objective_path(@objective), class:"is-pulled-right button is-black" %>
  </div>
</div>

app/views/objectives/index.html.erb
<h1>Objectives</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objectives.each do |objective| %>
      <tr>
        <td><%= link_to 'Show', objective %></td>
        <td><%= link_to 'Edit', edit_objective_path(objective) %></td>
        <td><%= link_to 'Destroy', objective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objective', new_objective_path %>

app/views/objectives/new.html.erb
<%= render 'shared/breadcrumb'%>
<%= render 'form', objective: @objective %>

<%= link_to 'Back', objectives_path %>

app/views/objectives/show.html.erb
<%= render 'shared/breadcrumb' %>

<div class="columns is-centered">
  <div class="column is-narrow">
    <div class="box">
      <% if policy(@objective.strategy).update_objective? %>
        <%= link_to 'Edit', edit_objective_path(@objective),
                          class: 'button  is-small is-rounded is-pulled-left' %>
      <% end %>
      <h1 class="title is-5 has-text-centered">
        <%= "#{@objective.name} #{controller_name.capitalize.singularize}" %>
      </h1>
      <table class="table is-striped">
        <caption>Attributes</caption>
        <tr>
          <th>Strategy</th>
          <td><%= link_to @strategy.name, strategy_path(@strategy) %></td>
        </tr>
        <tr>
          <th>Action</th>
          <td><%= @objective.action %></td>
        </tr>
        <tr>
          <th>Taregt</th>
          <td><%= @objective.target.name %></td>
        </tr>
        <tr>
          <th>Minimum Users</th>
          <td><%= @objective.min_ops %></td>
        </tr>
        <% if @objective.max_ops %>
          <tr>
            <th>Maximum Users</th>
            <td><%= @objective.max_ops %></td>
          </tr>
        <% end %>
        <tr>
          <th>Priority</th>
          <td><%= @objective.priority%></td>
        </tr>
        <tr>
          <th>Created at</th>
          <td><%= @objective.created_at %></td>
        </tr>
        <tr>
          <th>Updated at</th>
          <td><%= @objective.target.updated_at %></td>
        </tr>
        <% if @master %>
          <tr>
            <th>Master Objective</th>
            <td>
              <%= link_to(@master.name, objective_path(@master)) %>
            </td>
          </tr>
        <% end %>
        <% if @objective.slaves.count > 0 %>
          <tr>
            <th>Slave Objectives</th>
            <td>
              <%= @objective.slaves.count %>
            </td>
          </tr>
        <% end %>
        <% if @next %>
          <tr>
            <th>Next Objective</th>
            <td>
              <%= link_to(@next.name, objective_path(@next)) %>
            </td>
          </tr>
        <% end %>
        <% if @objective.previous.count > 0 %>
          <tr>
            <th>Previous Objectives</th>
            <td>
              <%= @objective.previous.count%>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
  <div class="column is-narrow">
    <div class="box">
      <button class='button new-recipe-btn is-rounded is-small'>
        New Recipe
      </button>
      <table class="table is-bordered">
        <caption class="title is-5">Recipes</caption>
        <thead>
          <tr>
            <th>Name</th>
            <th>Created By</th>
          </tr>
        </thead>
        <tbody>
          <% @recipes.each do |recipe| %>
            <tr>
              <td>
                <%= link_to recipe.name, recipe_path(recipe) %>
              </td>
              <td>
                <%= link_to recipe.commander.name, 
                            user_path(recipe.commander) %> 
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div class="modal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head" >
      <p class="modal-card-title">New Mode</p>
      <button class="delete close-btn" aria-label="close"></button>
    </header>
    <section class="modal-card-body">
      <div class="recipe-form">
        <%= render '/recipes/form', recipe: @recipe %>
      </div>
    </section>
  </div>
</div>