config/routes.rb
Rails.application.routes.draw do
  resources :loadouts
  resources :ingredients
  require 'sidekiq/web'

  mount SimpleDiscussion::Engine => "/forum"
  mount ActionCable.server => '/cable'

  authenticate :user, ->(op) { op.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'static_pages#about'

  resources :locations
  resources :respawns
  resources :modes
  resources :characters
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', 
                            registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
  resources :games
  resources :levels
  resources :directions
  resources :recipes
  resources :rooms
  resources :teams
  resources :objectives
  resources :strategies

  get '/about' => 'static_pages#about'
  get '/docs' => 'static_pages#docs'
  get '/strategies/xml/:uuid' => 'strategies#show_xml', as: 'strategy_xml'
  patch '/games/:id/switch/' => 'games#switch', as: 'switch_game'
  put '/users/api_key' => 'users#create_api_key', as: 'api_key'
  put '/teams/:id/link/:game_id' => 'teams#link_game', as: 'game_link'
  delete '/teams/:id/link/:game_id' => 'teams#unlink_game', as: 'game_unlink'
  post 'teams/:id/join' => 'teams#join_team', as: 'join_team'
  post 'teams/:id/change_title' => 'teams#change_member_title',
       as: 'change_member_title'
end

app/views/shared/_breadcrumb.html.erb
<nav class="breadcrumb is-centered" aria-label="breadcrumbs">
  <ul>
    <%= render "shared/breadcrumbs/game" if @game%> 
    <%= render "shared/breadcrumbs/strategies" if @strategy%> 
    <%= render "shared/breadcrumbs/strategy" if @strategy && @strategy.id%> 
    <%= render "shared/breadcrumbs/objective" if @objective && @objective.id%> 
    <%= render "shared/breadcrumbs/recipe" if @recipe && @recipe.id  %>
    <%= render "shared/breadcrumbs/direction" if @direction && @direction.id %>
    <%= render "shared/breadcrumbs/ingredient" if @ingredient && @ingredient.id %>
  </ul>
</nav>

app/views/shared/_footer.html.erb
<footer class="footer">
  <nav class="level is-mobile">
    <div class="level-item has-text-centered">
      <div>
        <a href="https://discord.gg/SW4P372" aria-label="Go to our Discord server">
          <i aria-hidden="true" class="fab fa-discord fa-2x fa-links"></i>
        </a>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <a href="https://twitter.com/minus1app" aria-label="Go to our Twitter page">
          <i aria-hidden="true" class="fab fa-twitter fa-2x fa-links"></i>
        </a>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <a href="https://www.reddit.com/r/Minus1/" aria-label="Go to our Reddit page">
          <i aria-hidden="true" class="fab fa-reddit fa-2x fa-links"></i>
        </a>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <a href="https://github.com/RonWalker22/minus1" aria-label="Go to our Github page">
          <i aria-hidden="true" class="fab fa-github fa-2x fa-links"></i>
        </a>
      </div>
    </div>
    <div class="level-item has-text-centered">
      <div>
        <a href="https://www.youtube.com/channel/UCoHtMzvmJ4LERM60EaGIH5g" aria-label="Go to our YouTube page">
          <i aria-hidden="true" class="fab fa-youtube fa-2x fa-links"></i>
        </a>
      </div>
    </div>
  </nav>
  <div class="has-text-centered">
    <%= image_tag 'tactical-sugar.png', alt: 'Tactical Sugar logo'%>
  </div>
</footer>

app/views/shared/_form-box-end.html.erb
    </div>
  </div>
</div>

app/views/shared/_form-box-start.html.erb
<div class="columns is-centered">
  <div class="column is-one-third">
    <h1 class="title is-5 has-text-centered">
    <%= "#{action_name.capitalize} #{controller_name.singularize.capitalize}"%>
    </h1>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <%= image_tag 'm1-logo.png', alt: 'Minus1
        logo.', id:'m1-logo'%>
      </a>

      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="main-navbar">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>

    <div id="main-navbar" class="navbar-menu">
      <div class="navbar-start">
        <a class="navbar-item" href="/">
          Home
        </a>
        <% if current_user && policy(Strategy).show? %>
          <%=  link_to "Strategies", strategies_path, class: 'navbar-item' %>
        <% end %>
        <% if user_signed_in? %>
          <a class="navbar-item" href=" <%= teams_path %>">
            Teams
          </a>
        <% end %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            More
          </a>

          <div class="navbar-dropdown">
            <%= link_to "Forum", simple_discussion_path, class: 'navbar-item' %>
            <hr class="navbar-divider">
            <%= link_to "About", about_path, class: "navbar-item" %>
            <hr class="navbar-divider">
            <%= link_to "Docs", docs_path, class: 'navbar-item',
            'data-turbolinks' => false%>
          </div>
        </div>
      </div>

      <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <%= @game ? @game.name : current_user.game_setting.name%>
          </a>
          <div class="navbar-dropdown">
            <%= link_to "All Games", games_path, class: 'navbar-item'%>
          </div>
        </div>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            <%= current_user.name %>
          </a>
          <div class="navbar-dropdown">
            <%= link_to "Profile", user_path(current_user), class: "navbar-item" %> 
            <hr class="navbar-divider">
            <%= link_to "Log out", destroy_user_session_path, method:
          :delete, class: "navbar-item" %>
          </div>
        </div>
        <% end %>
        <div class="navbar-item">
          <div class="buttons">
            <% unless user_signed_in? %>
              <%= link_to 'Login', new_user_session_path, class: "button" %>
              <%= link_to 'Sign Up', new_user_registration_path, class: "button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_index-end.html.erb
    </div>
  </div>
</div>

app/views/shared/_index-start.html.erb
<div class="columns is-centered">
  <div class="column is-two-thirds">
    <div class="box <%=myclass%>">
      <h1 class="title is-5 has-text-centered">
      <%= "#{@game.name} #{controller_name.capitalize}"%>
      </h1>

app/views/shared/_show-end.html.erb
    </div>
  </div>
</div>

app/views/shared/_show-start.html.erb
<div class="columns is-centered">
  <div class="column is-one-third">
    <div class="box">

app/views/shared/_spacer.html.erb
<hr/>