config/routes.rb
Rails.application.routes.draw do
  resources :loadouts
  resources :ingredients
  require 'sidekiq/web'

  mount SimpleDiscussion::Engine => "/forum"
  mount ActionCable.server => '/cable'

  authenticate :user, ->(op) { op.has_role?(:admin) } do
    mount Sidekiq::Web => '/sidekiq'
  end

  root to: 'static_pages#about'

  resources :locations
  resources :respawns
  resources :modes
  resources :characters
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks', 
                            registrations: 'users/registrations' }
  resources :users, only: [:index, :show]
  resources :games
  resources :levels
  resources :directions
  resources :recipes
  resources :rooms
  resources :teams
  resources :objectives
  resources :strategies

  get '/about' => 'static_pages#about'
  get '/docs' => 'static_pages#docs'
  get '/strategies/xml/:uuid' => 'strategies#show_xml', as: 'strategy_xml'
  patch '/games/:id/switch/' => 'games#switch', as: 'switch_game'
  put '/users/api_key' => 'users#create_api_key', as: 'api_key'
  put '/teams/:id/link/:game_id' => 'teams#link_game', as: 'game_link'
  delete '/teams/:id/link/:game_id' => 'teams#unlink_game', as: 'game_unlink'
  post 'teams/:id/join' => 'teams#join_team', as: 'join_team'
  post 'teams/:id/change_title' => 'teams#change_member_title',
       as: 'change_member_title'
end

app/models/respawn.rb
class Respawn < ApplicationRecord
  resourcify
  belongs_to :game
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  has_many :level_respawns, dependent: :delete_all
  has_many :level, through: :level_respawns
  has_many :ingredients, as: :piece
end

app/controllers/respawns_controller.rb
class RespawnsController < ApplicationController
  before_action :set_respawn, only: [:show, :edit, :update, :destroy]

  # GET /respawns
  # GET /respawns.json
  def index
    @respawns = Respawn.all
  end

  # GET /respawns/1
  # GET /respawns/1.json
  def show; end

  # GET /respawns/new
  def new
    @respawn = Respawn.new
  end

  # GET /respawns/1/edit
  def edit
    begin
      authorize @respawn
      @game = @respawn.game
    rescue Pundit::NotAuthorizedError
      flash[:alert] = "You are not authorized to edit this resource."
      redirect_to(request.referrer || root_path)
    end
  end

  # POST /respawns
  # POST /respawns.json
  def create
    @respawn = Respawn.new(respawn_params)
    levels = @respawn.game.levels.ids

    if @respawn.save
      params[:respawn][:level_id].each do |level_id|
        level_id = level_id.to_i
        next if levels.exclude?(level_id)

        LevelRespawn.create! level_id: level_id, respawn_id: @respawn.id
      end
      add_contributor(@respawn.game)
    else
      flash[:alter] = 'Respawn was not created.'
    end
    redirect_back fallback_location: root_path
  end

  # PATCH/PUT /respawns/1
  # PATCH/PUT /respawns/1.json
  def update
    authorize @respawn
    levels = @respawn.game.levels.ids

    if @respawn.update(respawn_params)
      LevelRespawn.where(respawn_id: @respawn.id).destroy_all
      params[:respawn][:level_id].each do |level_id|
        level_id = level_id.to_i
        next if levels.exclude?(level_id)

        LevelRespawn.create! level_id: level_id, respawn_id: @respawn.id
      end
    else
      flash[:notice] = 'Respawn was not created.'
    end
    redirect_to game_path(@respawn.game)
  end

  # DELETE /respawns/1
  # DELETE /respawns/1.json
  def destroy
    authorize @respawn
    unless @respawn.destroy
      flash[:alter] = 'Respawn was not destroyed.'
    end
    redirect_to game_path(@respawn.game)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_respawn
      @respawn = Respawn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def respawn_params
      params[:respawn][:user_id] = current_user.id
      params.require(:respawn).permit(:game_id, :name, :user_id)
    end
end

app/helpers/respawns_helper.rb
module RespawnsHelper
end

app/views/respawns/_form.html.erb
<%= form_with(model: respawn, local: true) do |form| %>
  <% if respawn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(respawn.errors.count, "error") %> prohibited this respawn from being saved:</h2>

      <ul>
      <% respawn.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :game_id, value: @game.id %>

  <div class="field">
    <%= form.label :name, class: 'label' %>
    <%= form.text_field :name, class: 'input', required: true %>
  </div>

  <div class="field select is-multiple">
  <%= form.collection_select(:level_id, @game.levels, :id, :name,
  {}, {required: true, multiple: true, include_hidden: false}) %>
  </div>

  <div class="actions">
    <%= form.submit class:"button is-link is-pulled-left"%>
  </div>
<% end %>

app/views/respawns/edit.html.erb
<div class="columns is-centered">
  <div class="column is-one-third">
    <% if @game.status == 'proposal' && policy(@respawn).destroy? %>	
      <%= link_to "Delete this respawn", respawn_path(@respawn), 	
                        method: :delete,	
                        data: { 	
                          confirm: 	
                          "Are you sure you want to delete #{@respawn.name}?" 	
                        }, 	
                        class: "button is-black is-pulled-right is-small is-rounded" %>	
    <% end %>
    <h1>Editing Respawn</h1>

    <%= render 'form', respawn: @respawn %>
    <%= link_to 'Cancel', game_path(@game), class:"is-pulled-right button is-black" %>
  </div>
</div>

app/views/respawns/index.html.erb
<h1>Respawns</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @respawns.each do |respawn| %>
      <tr>
        <td><%= respawn.game %></td>
        <td><%= respawn.name %></td>
        <td><%= link_to 'Show', respawn %></td>
        <td><%= link_to 'Edit', edit_respawn_path(respawn) %></td>
        <td><%= link_to 'Destroy', respawn, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Respawn', new_respawn_path %>

app/views/respawns/new.html.erb
<h1>New Respawn</h1>

<%= render 'form', respawn: @respawn %>

<%= link_to 'Back', respawns_path %>

app/views/respawns/show.html.erb
<p>
  <strong>Game:</strong>
  <%= @respawn.game %>
</p>

<p>
  <strong>Name:</strong>
  <%= @respawn.name %>
</p>

<%= link_to 'Edit', edit_respawn_path(@respawn) %> |
<%= link_to 'Back', respawns_path %>